version: "3"

networks:
  spring-network:
    external: true
    driver: bridge

services:
  app:
    platform: linux/amd64
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    networks:
      - spring-network
    depends_on:
      - mongodb
      - redis
    restart: always
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=kakaotalk
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
  redis:
    image: redis:alpine
    container_name: redis_boot
    command: redis-server --port 6379
    restart: always
    ports:
      - "6379:6379"
    networks:
      - spring-network
    volumes:
      - redis:/data
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    command: ["mongod", "--bind_ip", "0.0.0.0"]
    environment:
      MONGO_PORT: 27017
      MONGO_INITDB_DATABASE: kakaotalk
    ports:
      - "27017:27017"
    networks:
      - spring-network
    volumes:
      - mongodb:/data

volumes:
  redis:
    external: true
  mongodb:
    external: true
