address: localhost
port: 8080

spring:
  data:
    mongodb:
      #mongodb://devlabs123:devlabs123@kakaotalk.cluster-cezlsuk1t6pe.ap-northeast-2.docdb.amazonaws.com:27017/?ssl=true&ssl_ca_certs=global-bundle.pem&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false
      host: localhost
      port: 27017
      database: test
    redis:
      timeout: 600
      host: localhost
      port: 6379
    session:
      storage-type: redis
    jwt:
      secret: devlabs-secret

server:
  port: 8080
