spring:
  application:
    name: "kakaotalk"
  data:
    mongodb:
      host: "127.0.0.1"
      port: 27017
      authentication-database: "admin"
      database: "kakaotalk"
      username: "root"
      password: "root"
    redis:
      timeout: 600
      host: "127.0.0.1"
      port: 6379
  session:
    storage-type: "redis"

server:
  port: 8080
