spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: kakaotalk
    redis:
      timeout: 600
      host: localhost
      port: 6379
  session:
    storage-type: redis
server:
  port: 8080
