address: localhost
port: 8080

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: kakaotalk
      username: root
      password: root
    redis:
      timeout: 600
      host: localhost
      port: 6379
  session:
    storage-type: redis
server:
  port: 8080